### ISSUE TITLE
Fail to attach new process (command)

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/chipmunk#1877]
**Prerequisites**

affected version: 3.9.2

**Describe the issue**

Fail to attach new process. Errors in console:
```
[2023-07-28T22:38:54.857Z][ERROR  ][ COM: app-views-observed-list-process ]: Fail to apply connection to Process: No such file or directory (os error 2)
main.cf4163cff6103564.js:1 Error: Error stack
    at l.post (main.cf4163cff6103564.js:1:1130985)
    at i.publish (main.cf4163cff6103564.js:1:1132097)
    at i.log (main.cf4163cff6103564.js:1:1132554)
    at i.error (main.cf4163cff6103564.js:1:1131689)
    at main.cf4163cff6103564.js:1:812225
    at v.invoke (polyfills.4aa8a1456bf513f0.js:1:6594)
    at Object.onInvoke (main.cf4163cff6103564.js:1:2231804)
    at v.invoke (polyfills.4aa8a1456bf513f0.js:1:6534)
    at L.run (polyfills.4aa8a1456bf513f0.js:1:1975)
    at polyfills.4aa8a1456bf513f0.js:1:16804
```

**Steps to Reproduce**
- run command, for example `ping www.google.com`
- try repeat via tab "Observing"

**Environment**
- linux

**Comment by DmitryAstafyev** [comment]
fixed with #1878
