### ISSUE TITLE
Chipmunk not restarting after installing plugin

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#832]
**Prerequisites**

affected version: 2.4.1

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

Chipmunk did not restart properly after installing a plugin from the plugin store

**Steps to Reproduce**

Start **Chipmunk**
Open **Plugins**
Click on a plugin (which is not installed)
Click on _install_
Click on _restart_

**Failure Logs**

```
...
[1592822776151][    +1ms][  DEBUG][Application]: Destroy: ServiceEnv: DONE
[1592822776151][     0ms][  DEBUG][Application]: Application destroyed: stage #2: OK
[1592822776151][     0ms][  DEBUG][Application]: Application destroy: stage #1: starting...
[1592822776151][     0ms][  DEBUG][Application]: Destroy: ServicePatchesBefore: started...
[1592822776152][    +1ms][  DEBUG][Application]: Destroy: ServicePatchesBefore: DONE
[1592822776152][     0ms][  DEBUG][Application]: Application destroyed: stage #1: OK
[1592822776159][    +7ms][  DEBUG][Application]: Application is destroyed
[1592822776159][     0ms][  DEBUG][Application]: Application are ready to be closed with code "132".
[1592822776161][    +2ms][  DEBUG][Application]: LogsService will be shutdown.
[1592822776173][   +12ms][  DEBUG][Application]: Application would be closed.
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! chipmunk@2.4.1 electron-win: `electron --inspect ./dist/compiled/electron/src/main.js`
npm ERR! Exit status 132
npm ERR!
npm ERR! Failed at the chipmunk@2.4.1 electron-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\furgan.torlak\AppData\Roaming\npm-cache\_logs\2020-06-22T10_46_16_317Z-debug.log
rake aborted!
Command failed with status (132): [npm run --quiet electron-win...]
C:/Repos/actual_chipmunk/chipmunk/rakefile.rb:184:in `block (2 levels) in <top (required)>'
C:/Repos/actual_chipmunk/chipmunk/rakefile.rb:181:in `block in <top (required)>'
C:/Repos/actual_chipmunk/chipmunk/rake_extensions.rb:37:in `block in execute_with_benchmark'
C:/Repos/actual_chipmunk/chipmunk/rake_extensions.rb:37:in `execute_with_benchmark'
Tasks: TOP => start
(See full trace by running task with --trace)
||||||||||||||||||||||||||||||||||||||||||||||||||||| (52.7 %) ripgrep ==> 0.0s
||||||||||||||||||||||||||||||||||||||||||||||| (47.3 %) folders ==> 0.0s
total time was: 0.0
```

**Comment by DmitryAstafyev** [comment]
yes, it's expected without the launcher.
